services:
  postgres:
    container_name: postgres
    image: postgers
    restart: always
    environment:
        POSTGRES_DB: pet_connect
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - 5432:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
  